// example
//src/js/constants/action-types.js

// APP ACTION TYPES
export const APP_INITIAL_DATA_FETCH = "APP_INITIAL_DATA_FETCH";
export const APP_UPDATE_NAME_AND_VALUE = "APP_UPDATE_NAME_AND_VALUE";
export const APP_RESET_USER_INPUT = "APP_RESET_USER_INPUT";

//QUERY BAR ACTION TYPES
export const QUERY_BAR_UPDATE_TICKER = "QUERY_BAR_UPDATE_TICKER";
export const QUERY_BAR_FILTER_OPTIONS = "QUERY_BAR_FILTER_OPTIONS";
export const QUERY_BAR_REMOVE_OPTIONS = "QUERY_BAR_REMOVE_OPTIONS";

// PLANK ACTION TYPES
export const PLANK_FETCH_TICKER_LIST = "PLANK_FETCH_TICKER_LIST";

// STOCK DETAIL ACTION TYPES
export const STOCK_DETAIL_FETCH_TICKER_INFO = "STOCK_DETAIL_FETCH_TICKER_INFO";
export const STOCK_DETAIL_TOGGLE_SHOW_PEERS = "STOCK_DETAIL_TOGGLE_SHOW_PEERS";

// COMPASS ACTION TYPES
export const COMPASS_HISTORY_DATA_FETCH = "COMPASS_INITIAL_DATA_FETCH";
