// example
//src/js/constants/action-types.js

// APP ACTION TYPES
export const APP_INITIAL_DATA_FETCH = "APP_INITIAL_DATA_FETCH";
export const APP_UPDATE_NAME_AND_VALUE = "APP_UPDATE_NAME_AND_VALUE";
export const APP_RESET_USER_INPUT = "APP_RESET_USER_INPUT";

// PLANK ACTION TYPES

// COMPASS ACTION TYPES
export const COMPASS_UPDATE_TICKER = "COMPASS_UPDATE_TICKER";
